plugins {
    id 'java'
    id 'maven-publish'
    id 'com.gradleup.shadow' version '9.4.1'
}

test {
    useJUnitPlatform()
}

dependencies {
    compileOnly "org.jetbrains:annotations:${project.jbAnnoVersion}"
    testCompileOnly "org.jetbrains:annotations:${project.jbAnnoVersion}"

    implementation "org.ow2.asm:asm:${project.asmVersion}"
    testImplementation "org.ow2.asm:asm:${project.asmVersion}"

    testImplementation "org.junit.jupiter:junit-jupiter:${project.junitVersion}"
}

tasks.named('jar', Jar) {
    enabled = false
}

shadowJar {
    archiveClassifier = ''
    relocate 'org.objectweb.asm', 'io.github.revxrsal.libs.asm'
}

java {
    withSourcesJar()
    withJavadocJar()

    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 8
}

publishing {
    publications {
        shadow(MavenPublication) {
            groupId project.group
            artifactId project.name
            version project.version

            from components.shadow
            artifact sourcesJar
            artifact javadocJar
        }
    }
}
