plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.4.1'
}

group 'io.github.revxrsal'
version '1.2'

repositories {
    mavenCentral()
}

dependencies {
    def jbAnnoVersion = '26.1.0'

    compileOnly "org.jetbrains:annotations:${jbAnnoVersion}"
    testCompileOnly "org.jetbrains:annotations:${jbAnnoVersion}"

    def asmVersion = '9.9.1'

    implementation "org.ow2.asm:asm:${asmVersion}"
    testImplementation "org.ow2.asm:asm:${asmVersion}"

    testImplementation 'org.junit.jupiter:junit-jupiter:6.1.0-M1'
}

shadowJar {
    relocate 'org.objectweb.asm', 'io.github.revxrsal.libs.asm'
}

test {
    useJUnitPlatform()
}
